# Generated by Django 4.2 on 2025-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ejinews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnews',
            name='category',
            field=models.CharField(choices=[('government', '政治,経済'), ('entertainment', 'エンターテインメント'), ('sports', 'スポーツ')], max_length=50, verbose_name='ジャンル'),
        ),
    ]
